apiVersion: v1
kind: Secret
metadata:
  name: rust-ctf-secrets
  namespace: rust-ctf
type: Opaque
stringData:
  postgres-user: ctf
  postgres-password: change_me_db_password
  postgres-db: rust_ctf
  database-url: postgres://ctf:change_me_db_password@postgres:5432/rust_ctf
  redis-url: redis://redis:6379
  jwt-secret: change_me_with_at_least_32_characters
  default-admin-password: change_me_admin_password
  auth-smtp-password: ""
