name: lateral-weakpass-lab

services:
  jumpbox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ctf-jumpbox
    hostname: jumpbox
    environment:
      ROOT_PASSWORD: root
      USERNAME: alice
      USER_PASSWORD: 123456
    ports:
      - "2222:22"
    networks:
      lab_net:
        ipv4_address: 172.30.0.10

  internal-host:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ctf-internal-host
    hostname: internal-host
    environment:
      ROOT_PASSWORD: root
      USERNAME: bob
      USER_PASSWORD: 123456
    networks:
      lab_net:
        ipv4_address: 172.30.0.20

networks:
  lab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
