services:
  jumpbox:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: jumpbox
    environment:
      ROOT_PASSWORD: root
      USERNAME: alice
      USER_PASSWORD: 123456
    networks:
      lab_net:
        ipv4_address: {{SUBNET_HOST_10}}

  internal-host:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: internal-host
    environment:
      ROOT_PASSWORD: root
      USERNAME: bob
      USER_PASSWORD: 123456
    networks:
      lab_net:
        ipv4_address: {{SUBNET_HOST_20}}

networks:
  lab_net:
    driver: bridge
    ipam:
      config:
        - subnet: {{SUBNET}}
